robot_base_frame: $(arg prefix)base_footprint
transform_tolerance: 0.4
update_frequency: 5.0
publish_frequency: 5.0
obstacle_range: 3.0
#mark_threshold: 1
publish_voxel_map: true
navigation_map:
  enable: true
obstacles:
  observation_sources: b_scan_marking b_scan_clearing f_scan_marking f_scan_clearing rs_scan_marking rs_scan_clearing
  b_scan_marking: {
    topic: b_scan,
    data_type: LaserScan,
    clearing: false,
    marking: true,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0
    }
  b_scan_clearing: {
    topic: b_scan,
    data_type: LaserScan,
    clearing: true,
    marking: false,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0,
    }
  rs_scan_marking: {
    topic: rs_scan,
    data_type: LaserScan,
    clearing: false,
    marking: true,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0
    }
  rs_scan_clearing: {
    topic: rs_scan,
    data_type: LaserScan,
    clearing: true,
    marking: false,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0,
    }
  f_scan_marking: {
    topic: f_scan,
    data_type: LaserScan,
    clearing: false,
    marking: true,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: 0.13,
    max_obstacle_height: 0.25,
    }
  f_scan_clearing: {
    topic: f_scan,
    data_type: LaserScan,
    clearing: true,
    marking: false,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: 0.13,
    max_obstacle_height: 0.25,
    }
  scan_marking: {
    topic: scan,
    data_type: LaserScan,
    clearing: false,
    marking: true,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0,
    }
  scan_clearing: {
    topic: scan,
    data_type: LaserScan,
    clearing: true,
    marking: false,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0,
    }
virtual_walls_map:
  map_topic: /virtual_walls/map
  use_maximum: true
