map_type: costmap
#origin_z: 0.0
#z_resolution: 1
#z_voxels: 2

obstacle_range: 2.5            #Khoảng cách tới vật cản (mét)
raytrace_range: 5.0

publish_voxel_map: false
transform_tolerance: 1.0
meter_scoring: false

#LxWXH = 0.76x0.5x0.327
footprint: [[-0.38, -0.25], [-0.38, 0.25], [0.38, 0.25], [0.38, -0.25]] # Khung Xung quanh AGV (x,y)
footprint_padding: 0.05 #Khoảng cách căn lề  khung
robot_radius: 0.25

#plugins:
#- {name: obstacle_3d_layer,       type: "costmap_2d::VoxelLayer"}
#- {name: static_layer,            type: "costmap_2d::StaticLayer"}
#- {name: obstacle_2d_layer,       type: "costmap_2d::ObstacleLayer"}
#- {name: inflater_layer,          type: "costmap_2d::InflationLayer"}

obstacle_2d_layer:
  enable: true
  track_unknown_space: true
  observation_sources: scan scan2 scan3
  scan: {
      sensor_frame: depth_link, 
      data_type: LaserScan, 
      topic: scanbypoint, 
      marking: true, 
      clearing: true, 
      min_obstacle_height: -0.5, 
      max_obstacle_height: 1.0, 
      obstacle_range: 2.5, 
      raytrace_range: 3.0,
      expected_updata_rate: 1
      }

  scan2: {
      sensor_frame: laser_frame, 
      data_type: LaserScan, 
      topic: sensor_laser/scan, 
      marking: true, 
      clearing: true, 
      min_obstacle_height: 0.0, 
      max_obstacle_height: 1.0, 
      obstacle_range: 2.5, 
      raytrace_range: 3.0,
      expected_updata_rate: 1
      }

  scan3: {
      sensor_frame: sickscan1_link, 
      data_type: LaserScan, 
      topic: sickscan/scan1, 
      marking: true, 
      clearing: true, 
      min_obstacle_height: 0.0, 
      max_obstacle_height: 1.0, 
      obstacle_range: 2.5, 
      raytrace_range: 3.0,
      expected_updata_rate: 1
      }

obstacle_3d_layer:
  enabled: true
  origin_z: 0.0
  z_resolution: 0.1
  z_voxels: 0.9
  unknown_threshold: 0
  mark_threshold: 0
  combination_method: 1   
  # for debugging only, let's you see the entire voxel grid
  publish_voxel_map: false
  max_obstacle_height: 3.0
  observation_sources: 3d_cloud

  3d_cloud: {
      sensor_frame: camera_depth_optical_frame, 
      data_type: PointCloud2, 
      topic: depth/color/points, 
      marking: true, clearing: true, 
      min_obstacle_height: 0.0, 
      max_obstacle_height: 2.0, 
      obstacle_range: 2.5, 
      raytrace_range: 3.0,
      expected_updata_rate: 1
      }


inflater_layer:
  inflation_radius: 0.3 #Khoảng cách với tường
  cost_scaling_factor: 15.0

static_layer:
  enabled:              true
