# Choose planners                                            
#base_local_planner: "teb_local_planner/TebLocalPlannerROS"      
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
#base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_global_planner: "global_planner/GlobalPlanner"    

shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 5.0

planner_frequency: 10.0
planner_patience: 10.0

oscillation_timeout: 0.1
oscillation_distance: 0.01

recovery_behavior_enabled: false  #Cho phép tự quay để  tìm lại vị trí nếu bị mất
clearing_rotation_allowed: true

recovery_behaviors:
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

aggressive_reset:
  reset_distance: 0.0
  layer_names: ["obstacle_2d_layer"]

# global_planner params                                      
GlobalPlanner:                                               
  default_tolerance: 0.2                                     
  cost_factor: 0.5489                                        
  neutral_cost: 66                                           
  lethal_cost: 253
  
  easy_deceleration: false #flag for simplified planning of deceleration at the goal. default: false
  easy_turn_at_start: false #flag for simplified planning of turn in place at the start. default: false
  easy_turn_at_goal: false #flag for simplified planning of turn in place at the goal. default: false
